#!/bin/bash
LAN_IP=$(hostname -I | grep -E -o '([0-9]{1,3}[\.]){3}[0-9]{1,3}')
for i in 0 1 2 3 4 5 6 7 8 9
do
	vncserver -kill :$i >/dev/null 2>&1
done
rm -rf /tmp/.X*-lock
rm -rf /tmp/.X11-unix/X*
vncserver -geometry 1366x768 >/dev/null 2>&1
vncserver -geometry 1280x800 >/dev/null 2>&1
vncserver -geometry 1440x720 >/dev/null 2>&1
vncserver -geometry 1280x960 >/dev/null 2>&1
echo ""
echo "VNC Server has started"
echo "----------------------"
echo "[VNC Address 1] $LAN_IP:1 (Desktop)"
echo "[VNC Address 2] $LAN_IP:2 (Laptop)"
echo "[VNC Address 3] $LAN_IP:3 (Mobile)"
echo "[VNC Address 3] $LAN_IP:4 (Tablet)"
echo ""
